### PR TITLE
fix: Attempting to patch the missing tool message bug

### LINKED ISSUE #204: Issue with Parallel Tool calling the `QuerySQLDataBaseTool`
If the ai calls `QuerySQLDataBaseTool` more than once in a single shot, we get the `openai.BadRequestError: Error code: 400` error `"An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'`

Reason for this is because inside the `QuerySQLDataBaseTool`, we append a tool message and an ai message each time
image

And so we get tool messages separated by ai messages, which is problematic
image

This can also happen if another tool is used alongside the `QuerySQLDataBaseTool`

### PR DESCRIPTION
**Pull request by RamiAwar**
Closes #204

### CODE REVIEW

**Review by anthony2261 — APPROVED** [review]
This looks fine to me, but it doesn't feel like a fix. Messages will lose their coherence. If you look at the `QuerySQLDataBaseTool` for example, the output is a ToolMessage and an AIMessage that is supposed to follow the ToolMessage. But with the current changes, the AIMessage will be pushed to the end with the rest of the non-ToolMessages, which becomes confusing. Are we able to just merge the AIMessage content into the ToolMessage? Was there a specific reason for us to separate them?

**Comment by RamiAwar** [comment]
Reason to separate them was to ensure that all tool messages come first (from across calls to tools) and all other messages come later. 

but if you said that this didn't fix the bug, then we can revert this cause it's a useless change and only adds confusion and doesn't fix the problem

**Comment by anthony2261** [comment]
> Reason to separate them was to ensure that all tool messages come first (from across calls to tools) and all other messages come later.

I meant why seperate the content into ToolMessage and AIMessage, instead of just having ToolMessage. In `QuerySQLDataBaseTool.get_response`, we have a tool message with content like
```python
content="Query executed successfully - here is the returned data description. "
"I cannot view the data for security reasons but the user should be able to see the results!"
f"{data_description}"
```

And then an AIMessage with content like:
```python
"Now that I have the data, I can analyze it and consider regenerating the query."
...
```
Why not add the content of the AIMessage into the ToolMessage and get rid of the AIMessage altogether?

**Comment by anthony2261** [comment]
@RamiAwar check this: https://github.com/RamiAwar/dataline/commit/5a8058da66ae72ba8f5bf37596b5ea18c335887f
This fixed things for me without having to create the split between tool_messages and other messages like we do in this branch. Also, this makes it such that each tool returns one ToolMessage and nothing else

**Pull request closed without merging**
