### PR TITLE
Add mysql python connector used by sqlalchemy

### LINKED ISSUE #229: MySQL connection seems to be broken
Getting some Sentry errors about broken MySQL connections. 

Should look into this, and also write a blog post about integration.

### PR DESCRIPTION
**Pull request by anthony2261**
Support mysql connections. DSN example: mysql://<username>:<password>@<host>:<port>/<db>

Also tested in pyinstaller binary

Closes #229

### CODE REVIEW

**Comment by RamiAwar** [comment]
I remember I already added this connector before:
image


So we don't need this other connector, Pymysql seems to be recommended by SQLAlchemy.

I'll look into the connection string tho, we probably still need that part except update it to pymysql connector.

**Comment by RamiAwar** [comment]
Reason why I chose it back then: 

image

**Comment by RamiAwar** [comment]
Also FYI we have DSN validation already in the schemas for DSN, so the mysql connector replacement should happen there instead. I remember only cause I've written that code 😄

**Comment by anthony2261** [comment]
@RamiAwar good catch, I've replaced the mysql connector to use pymsql, and moved the dsn validation to the right place

**Review by RamiAwar — APPROVED** [review]

**Pull request merged**
