### PR TITLE
Expandable chart and codeblock

### PR DESCRIPTION
**Pull request by filip65**

### CODE REVIEW

**Comment by anthony2261** [comment]
Hey @filip65, thanks for the PR! The minimize functionality works well and the animations look awesome.

I found one issue with the `overflow-hidden` class being used inside the `Minimizer`, sometimes we need to show some things outside of the box (like with `absolute` positioned elements), and `overflow-hidden` will constrain us.

For example, if a `CodeBlock` is tied to a chart, we show a tooltip at the top. The two photos below are with your changes and without, respectively:

image
image

Another thing I would modify is the fact that we have to use `Minimizer` twice, whereas we could just be doing it once:

image
image

**Review by anthony2261 — CHANGES_REQUESTED** [review]
(See comment above)

**Comment by anthony2261** [comment]
I've refactored the `Minimizer` code a bit so that it behaves more like the code in `DynamicTable.tsx`, i.e. it adds/removes the elements from the DOM instead of hiding them with css magic. This solves the issue of `overflow-hidden` hiding things we want to show.

We can merge as is, but it would be good to use the `Minimizer` component in the `DynamicTable` component, do you think you can try that @filip65?

**Comment by filip65** [comment]
Hi @anthony2261, I used that css magic, because there was problem with Codeblock. After minimize and maximize textarea looses it's value and when you try to type, it clears whole code... But I fixed this issue and also added Minimized to Dynamic table as you wanted.

**Comment by anthony2261** [comment]
Ooh good catch with the CodeBlock bug, and thanks for the fix! This is looking pretty neat to me :)

**Review by anthony2261 — APPROVED** [review]

**Pull request merged**
