### PR TITLE
Remove default pragma FK ON for migrations

### PR DESCRIPTION
**Pull request by anthony2261**

### CODE REVIEW

**Review by RamiAwar — APPROVED** [review]

**Review by RamiAwar — CHANGES_REQUESTED** [review]
This might break the initial migration though no? If there are no FK?

Maybe doesn't have an effect since there is no data? idk wdyt?

**Comment by anthony2261** [comment]
@RamiAwar Initial migration should not be affected because it's just creating tables and not data. The role of the pragma command is to enforce FK validation, not creating or removing constraints. I.E. if we have a table with a column that foreign keys to another table, this will always be the case regardless of the pragma FK status. The difference is that if the pragma is off, we are able to create an entry with a non-existing FK and sqlite will not throw an error, but if pragma is on we will get an error

**Review by RamiAwar — APPROVED** [review]

**Comment by RamiAwar** [comment]
Add a contribution guide to the repository

* Add a new `CONTRIBUTING.md` file with instructions for contributing to the project.
* Update `backend/README.md` to include a section on Alembic migrations with the same reminder for PRAGMA FK commands.

---

**Comment by anthony2261** [comment]
@RamiAwar would be good to include why the Pragma command was removed and more importantly what to lookout for if the contributor decides to add pragma fk on: the potential loss of data

**Comment by RamiAwar** [comment]
We should also include it in the PR description here (not just in the readme). 

At this point SQLite needs it's own readme of gotchas lol. Maybe we link those articles somewhere. It's really a lot of headache but the portability is worth it...

**Pull request merged**
